//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 7 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `ballCount`.
    var ballCount: RswiftResources.ColorResource { .init(name: "ballCount", path: [], bundle: bundle) }

    /// Color `boardBackGround`.
    var boardBackGround: RswiftResources.ColorResource { .init(name: "boardBackGround", path: [], bundle: bundle) }

    /// Color `emptyCount`.
    var emptyCount: RswiftResources.ColorResource { .init(name: "emptyCount", path: [], bundle: bundle) }

    /// Color `labelText`.
    var labelText: RswiftResources.ColorResource { .init(name: "labelText", path: [], bundle: bundle) }

    /// Color `outCount`.
    var outCount: RswiftResources.ColorResource { .init(name: "outCount", path: [], bundle: bundle) }

    /// Color `strikeCount`.
    var strikeCount: RswiftResources.ColorResource { .init(name: "strikeCount", path: [], bundle: bundle) }
  }
}